name: CI

env:
  k8sclustername: 
  resourceGroupName:
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  # The types of runners this will run on windows-latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: Azure/aks-set-context@v1
      with:
        creds:
        cluster-name:
        resource-group:
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          KubernetesManifest/nginx.yml
